### ISSUE TITLE
OOT Undefined Symbol in GNU Radio 3.8

### ISSUE THREAD

**Issue by DeliciousStrawberryPocky** [gnuradio/gnuradio#2798]
I am trying to port my OOT modules to GNU Radio 3.8. I have been doing this by creating new modules using gr_modtool, creating blocks with the same name as my original blocks and then copying the .cc and .h files to the right places. The newly-imported OOT module compiles just fine, but when i try to run a flowgraph to test them out, I get the error: 

AttributeError: module 'Receivers' has no attribute 'fll_band_edge_modified_cc'

I ran python import in my build directory to see if any error pop. I got the error:

undefined symbol: _ZN2gr6filter6kernel26fir_filter_with_buffer_cccD1Ev

Which made me think that my cmake is not linking to gnu lib properly. So, I followed the OOT GNU Radio 3.8 porting guide and I added "COMPONENTS filter blocks fft" in the find_package call in the main cmake file to no avail.

I put the OOT in this repo:

https://github.com/DeliciousStrawberryPocky/testblocks.git

Please let me know if i am doing anything wrong. The OOT module and the blocks work in GNU 3.7.

**Comment by buaawang** [comment]
Hi, I am facing the same problem with you, have you update your git? I watch your OOT, and try it. but still the same bug. I am using the GNU 3.7

**Comment by DeliciousStrawberryPocky** [comment]
I didn't push the corrected OOT module. Can you share your OOT with me? Maybe I can help with that.

**Comment by shiwang-Xing** [comment]
Hello, My code has upload to the git now, thank you for your attention.
[git@github.com:shiwang-Xing/gr-sss1.git](url)

**Comment by shiwang-Xing** [comment]
I'm sorry that maybe the url doesn't work, hope this can work[https://github.com/shiwang-Xing/gr-sss1](url)

**Comment by shiwang-Xing** [comment]
OK, I read your procedure carefully and just figure it out, thank you for your guidance!!!

**Comment by DeliciousStrawberryPocky** [comment]
Awesome. Well, I am glad that helped you out!
