### PR TITLE
GRC: Fix for GRC crash in case of flowgraph error

### LINKED ISSUE #2327: GRC: hier block with multiple message pad source ports crashes GRC
If you generate `/gr-blocks/examples/msg_passing/hier/test_msg_hier.grc` it does produce an invalid `.grc` file which prevents GRC from loading. GRC will complain about non-unique port IDs. If you look at the generated `.grc` file, this is indeed the case.

What makes that issue really annoying is the fact, that once this flowgraph is generated, GRC will crash because it can't load that particular flowgraph.

### PR DESCRIPTION
**Pull request by aru31**
Fixes #2327

### CODE REVIEW

**Comment by aru31** [comment]
As in this [comment](https://github.com/gnuradio/gnuradio/issues/2327#issuecomment-473921769), I figured out why `Messages.send()` didn't work, it was because the `Message.send(message)` function loaded the message in GRC before it even opened, so fix for this was to define a global variable that stored the error, and thus print it on the terminal after GRC loaded.

**Comment by mbr0wn** [comment]
...and no one complained about them, either.

**Comment by bastibl** [comment]
This seems to break GRC for me:
```
Error: module 'gnuradio.grc.core.Messages' has no attribute 'flowgraph_error'
>>> Failure
Traceback (most recent call last):
  File "/home/basti/usr/gnuradio/lib/python3.7/dist-packages/gnuradio/grc/gui/MainWindow.py", line 263, in new_page
    if str(Messages.flowgraph_error) is not None:
AttributeError: module 'gnuradio.grc.core.Messages' has no attribute 'flowgraph_error'
```

**Comment by mbr0wn** [comment]
Yeah it breaks GRC. I pushed an emergency fixup. Sorry, I merged to many PRs yesterday I must have thought I tested it when I didn't.

**Comment by mbr0wn** [comment]
@aru31 Can you see if this still fixes your problem after the fixup commit?

**Comment by aru31** [comment]
@mbr0wn Sorry, for the bad pull request, I didn't initialize the global variables which caused GRC to break.
