### ISSUE TITLE
Compilation failure with MinGW

### ISSUE THREAD

**Issue by argilo** [gnuradio/gnuradio#7194]
GNU Radio's `main` branch fails to build with MinGW:
```
FAILED: gr-fft/lib/CMakeFiles/gnuradio-fft.dir/fft.cc.obj 
D:\a\_temp\msys64\mingw64\bin\c++.exe -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DFFTW3F_THREADS -DFMT_SHARED -DGR_MPLIB_GMP -DGR_PERFORMANCE_COUNTERS -DMS_WIN64 -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -Dgnuradio_fft_EXPORTS -ID:/a/_temp/gnuradio/gr-fft/lib/../include -ID:/a/_temp/gnuradio/gnuradio-runtime/lib/../include -ID:/a/_temp/gnuradio/build/gnuradio-runtime/lib/../include -ID:/a/_temp/gnuradio/gnuradio-runtime/lib/pmt/../../include -ID:/a/_temp/gnuradio/gnuradio-runtime/include -ID:/a/_temp/gnuradio/build/gnuradio-runtime/include -Wsign-compare -Wall -Wno-uninitialized -fcx-limited-range -O3 -DNDEBUG -std=c++17 -Winvalid-pch -include D:/a/_temp/gnuradio/build/gr-fft/lib/CMakeFiles/gnuradio-fft.dir/cmake_pch.hxx -MD -MT gr-fft/lib/CMakeFiles/gnuradio-fft.dir/fft.cc.obj -MF gr-fft\lib\CMakeFiles\gnuradio-fft.dir\fft.cc.obj.d -o gr-fft/lib/CMakeFiles/gnuradio-fft.dir/fft.cc.obj -c D:/a/_temp/gnuradio/gr-fft/lib/fft.cc
D:/a/_temp/gnuradio/gr-fft/lib/fft.cc: In function 'void gr::fft::wisdom_lock_init()':
D:/a/_temp/gnuradio/gr-fft/lib/fft.cc:79:36: error: cannot convert 'const std::filesystem::__cxx11::path::value_type*' {aka 'const wchar_t*'} to 'const char*'
   79 |         open(wisdom_lock_file.c_str(), O_WRONLY | O_CREAT | O_NOCTTY | O_NONBLOCK, 0666);
      |              ~~~~~~~~~~~~~~~~~~~~~~^~
      |                                    |
      |                                    const std::filesystem::__cxx11::path::value_type* {aka const wchar_t*}
```
It appears this was caused by #7136.

/cc @marcusmueller

**Comment by argilo** [comment]
This came up in a Gqrx CI run: https://github.com/gqrx-sdr/gqrx/actions/runs/8284831347/job/22671242447

**Comment by Mr-Precise** [comment]
I believe this is the same issue as in #7156.
I wasn't able to fix it...

**Comment by argilo** [comment]
Yep, looks like this is a duplicate.
