### ISSUE TITLE
gr_modtool bind broken

### ISSUE THREAD

**Issue by drmpeg** [gnuradio/gnuradio#7907]
### What happened?

```gr_modtool bind```fails with the following:

```
gr_modtool bind subframemapper_cc
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, imp, stat
Traceback (most recent call last):
  File "/opt/gnuradio-3.10.0git/bin/gr_modtool", line 18, in <module>
    cli()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1132, in invoke
    cmd_name, cmd, args = self.resolve_command(ctx, args)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1171, in resolve_command
    cmd = self.get_command(ctx, cmd_name)
  File "/opt/gnuradio-3.10.0git/lib/python3.8/site-packages/gnuradio/modtool/cli/base.py", line 76, in get_command
    mod = import_module('gnuradio.modtool.cli.' + cmd_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gnuradio-3.10.0git/lib/python3.8/site-packages/gnuradio/modtool/cli/bind.py", line 39, in <module>
    def cli(**kwargs):
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 151, in decorator
    _param_memo(f, ArgumentClass(param_decls, **attrs))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1808, in __init__
    Parameter.__init__(self, param_decls, required=required, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'
```

### System Information

OS: (Linux Ubuntu 20.04)
Build from source

### GNU Radio Version

3.11-git (main)

### Specific Version

0.0.0.0

### Steps to Reproduce the Problem

I've bisected this issue to commit b92a696da1b3b24256eb4046b203733dec401b2e "modtool: add shell completion" and the associated shell completion commits.

### Relevant log output

```shell

```

**Comment by AsriFox** [comment]
I've tracked this issue to 1ecb856, and it occurs because of `shell_completion` parameter in `click.argument`, which was named `autocomplete` before Click 8.0.0, while Ubuntu 20.04 only provides 7.0-3.

Workaround: when using Click 7.0 (e.g. in Ubuntu 20.04), change `shell_completion` to `autocomplete` in [base.py](https://github.com/gnuradio/gnuradio/blob/1ecb85657548c616245d475297cf900e10def316/gr-utils/modtool/cli/base.py#L163) and [update.py](https://github.com/gnuradio/gnuradio/blob/1ecb85657548c616245d475297cf900e10def316/gr-utils/modtool/cli/update.py#L31).

**Comment by drmpeg** [comment]
Thanks.
