### PR TITLE
Fix MinGW build and std::fs issue

### LINKED ISSUE #7156: Build problem with MinGW (filesystem error)
### What happened?

Change https://github.com/gnuradio/gnuradio/commit/5173f01788a7e3c95e07286dbfca22e8b75d5273 caused an error when compiling with MinGW gcc.
Before this everything was fine.

### System Information

Host OS: Linux Ubuntu based 20.04 amd64
Compiler: GCC 11.4, mingw-w64 11.0.1 (custom toolchain)
GR Installation Method: Cross-compiling

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-668-gc2d1b5c5

### Steps to Reproduce the Problem

In `gr-fft/lib/fft.cc` I replaced the code blocks wrapped in `_MSC_VER` with `_WIN32`, and the build was successful.
But when trying to use Gnuradio it results in an error:
`filesystem error: cannot create directory: File exists [C:]`

### Relevant log output

```shell
terminate reached from thread id: 124Got std::system_error
filesystem error: cannot create directory: File exists [C:]
```

### LINKED ISSUE #7194: Compilation failure with MinGW
GNU Radio's `main` branch fails to build with MinGW:
```
FAILED: gr-fft/lib/CMakeFiles/gnuradio-fft.dir/fft.cc.obj 
D:\a\_temp\msys64\mingw64\bin\c++.exe -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DFFTW3F_THREADS -DFMT_SHARED -DGR_MPLIB_GMP -DGR_PERFORMANCE_COUNTERS -DMS_WIN64 -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -DSPDLOG_SHARED_LIB -DWIN32_LEAN_AND_MEAN -D_USE_MATH_DEFINES -Dgnuradio_fft_EXPORTS -ID:/a/_temp/gnuradio/gr-fft/lib/../include -ID:/a/_temp/gnuradio/gnuradio-runtime/lib/../include -ID:/a/_temp/gnuradio/build/gnuradio-runtime/lib/../include -ID:/a/_temp/gnuradio/gnuradio-runtime/lib/pmt/../../include -ID:/a/_temp/gnuradio/gnuradio-runtime/include -ID:/a/_temp/gnuradio/build/gnuradio-runtime/include -Wsign-compare -Wall -Wno-uninitialized -fcx-limited-range -O3 -DNDEBUG -std=c++17 -Winvalid-pch -include D:/a/_temp/gnuradio/build/gr-fft/lib/CMakeFiles/gnuradio-fft.dir/cmake_pch.hxx -MD -MT gr-fft/lib/CMakeFiles/gnuradio-fft.dir/fft.cc.obj -MF gr-fft\lib\CMakeFiles\gnuradio-fft.dir\fft.cc.obj.d -o gr-fft/lib/CMakeFiles/gnuradio-fft.dir/fft.cc.obj -c D:/a/_temp/gnuradio/gr-fft/lib/fft.cc
D:/a/_temp/gnuradio/gr-fft/lib/fft.cc: In function 'void gr::fft::wisdom_lock_init()':
D:/a/_temp/gnuradio/gr-fft/lib/fft.cc:79:36: error: cannot convert 'const std::filesystem::__cxx11::path::value_type*' {aka 'const wchar_t*'} to 'const char*'
   79 |         open(wisdom_lock_file.c_str(), O_WRONLY | O_CREAT | O_NOCTTY | O_NONBLOCK, 0666);
      |              ~~~~~~~~~~~~~~~~~~~~~~^~
      |                                    |
      |                                    const std::filesystem::__cxx11::path::value_type* {aka const wchar_t*}
```
It appears this was caused by #7136.

/cc @marcusmueller

### PR DESCRIPTION
**Pull request by marcusmueller**
## Description

GNU Radio ain't done if Gqrx ain't run, or so.

- fft: check for _WIN32, not only for _MSC_VER
- runtime/sys_paths: helper function for ensuring paths exist, recursively
- syspaths/ensure directory exists: MinGW Drive Letter workaround

## Related Issue

Closes #7194
Closes #7156

## Which blocks/areas does this affect?

Needed to centralize the creation of config/storage paths, so introduced new API function `gr::paths::utilities::ensure_directory`. Then, moved the bespoke directory creation out of the circbuf prefs and fft.cc.

So, this affects

- MinGW builds
- fft.cc
- circbuf prefs

but none of that in a way that changes current behaviour

## Testing Done

added test, coordinated with @argilo to get a Gqrx test build

## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [x] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [x] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [x] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by argilo** [comment]
I can confirm that this compiles and runs properly in Gqrx's Windows build.

That said, conditionally compiled code is a magnet for bugs, so let me think about whether there might be a way to avoid it.

**Comment by argilo** [comment]
Could `ensure_directory` be replaced by `std::filesystem::create_directories`?

File: gr-fft/lib/fft.cc [hunk 1]
```diff
@@ -104,7 +97,7 @@ static void unlock_wisdom()
 static void import_wisdom()
 {
     auto wisdom_path = gr::paths::cache() / WISDOM_FILENAME;
-#ifdef _MSC_VER
+#if defined(_MSC_VER) || defined(_WIN32)
```
Comment (argilo) [inline gr-fft/lib/fft.cc:100]: Is the conditional code necessary? The `.string().c_str()` version appears to work on Linux at least.

**Comment by marcusmueller** [comment]
'doh. @argilo `std::filesystem::create_directorie`**`s`** is a C++17 feature that escaped my knowledge. Yeah, let's not do this all here then.
