### PR TITLE
Backwards compatibility fix for pygtk 2.16 (centos6).

### PR DESCRIPTION
**Pull request by morse-michael**
Hi all,

After building gnuradio maint branch on Centos6 & running gnuradio-companion I was getting these errors:

> <<< Welcome to GNU Radio Companion 3.7.10.1 >>>
> 
> Block paths:
>         /tools/gnuradio/install/20160824-maint/share/gnuradio/grc/blocks
> Traceback (most recent call last):
>   File "/tools/gnuradio/install/20160824-maint/lib64/python2.7/site-packages/gnuradio/grc/gui/ActionHandler.py", line 397, in _handle_action
>     main.update_panel_visibility(main.BLOCKS, action.get_active())
>   File "/tools/gnuradio/install/20160824-maint/lib64/python2.7/site-packages/gnuradio/grc/gui/MainWindow.py", line 200, in update_panel_visibility
>     self.btwin.set_visible(visibility)
> AttributeError: 'BlockTreeWindow' object has no attribute 'set_visible' 

Had to make some changes to grc/gui/MainWindow.py to work around this issue, fix is similar to the following commit: http://gnuradio.org/redmine/projects/gnuradio/repository/revisions/56b13077335a814f3a72c8c759209bcc484ec712/diff/grc/gui/ActionHandler.py

Cheers,

Mcihael

### CODE REVIEW

**Comment by jmcorgan** [comment]
@skoslowski

**Comment by jmcorgan** [comment]
@sdh11 This looks trivial but I need your :+1: since Sebastian is not able to look at this right now.

**Comment by sdh11** [comment]
Thanks for catching this; I did not realize those functions were 2.22+. Can you use the get_property('visible') and set_property('visible', visibility) functions rather than the flags?

**Comment by jmcorgan** [comment]
@morse-michael Need response

**Comment by morse-michael** [comment]
Sorry, haven't had a chance to test this yet, will take a look later today...

**Comment by morse-michael** [comment]
Still works with pygtk 2.16 when I use get_property('visible') instead of the flags, see https://github.com/gnuradio/gnuradio/pull/901/commits/b358bbf73c0e489bad07833de2abe869f55f75f6

**Comment by jmcorgan** [comment]
I squashed these two commits and fixed the commit message per our usual practice.  Thanks
