### PR TITLE
grc: cpp code generation is wrong

### LINKED ISSUE #7488: gr-qtgui/examples/c++/gui_sink.grc has c++ compilation error
### What happened?

Running gr-qtgui/examples/c++/gui_sink.grc generates c++ compilation error

image

### System Information

OS: Ubuntu 24.04
GR Installation Method: source

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-809-g5c30d92b

### Steps to Reproduce the Problem

Open flowgraph, press run button

### Relevant log output

_No response_

### LINKED ISSUE #7500: gr-qtgui/examples/c++/Number_Sink.grc compilation error
### What happened?

Starting flowgraph gr-qtgui/examples/c++/Number_Sink.grc throws a compilation error and will not run to completion.

### System Information

OS: Ubuntu 24.04
GR Installation Method: source

### GNU Radio Version

3.11-git (main)

### Specific Version

v3.11.0.0git-816-g30a0aa91

### Steps to Reproduce the Problem

Run the flowgraph

### Relevant log output

```shell
Generating: "/home/matt/gnuradio/gr-qtgui/examples/c++/Number_Sink"
>>> Warning: The block 'blocks_throttle_0' is deprecated.

Executing: cmake .. && cmake --build . -j3 && cd ../.. && /usr/bin/x-terminal-emulator -e /home/matt/gnuradio/gr-qtgui/examples/c++/Number_Sink/build/Number_Sink

-- Using GMP.
-- User set python executable /usr/bin/python3
CMake Warning (dev) at /usr/local/lib/cmake/gnuradio/GrPython.cmake:21 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake:37 (include)
  CMakeLists.txt:12 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/lib/cmake/gnuradio/GrPython.cmake:27 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  /usr/local/lib/cmake/gnuradio/GnuradioConfig.cmake:37 (include)
  CMakeLists.txt:12 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- QWT Version: 6.1.4
-- Build type not specified: defaulting to release.
-- Configuring done (0.3s)
-- Generating done (0.0s)
-- Build files have been written to: /home/matt/gnuradio/gr-qtgui/examples/c++/Number_Sink/build
[  0%] Built target Number_Sink_autogen_timestamp_deps
[ 20%] Automatic MOC for target Number_Sink
[ 20%] Built target Number_Sink_autogen
[ 40%] Building CXX object CMakeFiles/Number_Sink.dir/Number_Sink.cpp.o
/home/matt/gnuradio/gr-qtgui/examples/c++/Number_Sink/Number_Sink.cpp:115:6: error: redefinition of ‘void Number_Sink::closeEvent(QCloseEvent*)’
  115 | void Number_Sink::closeEvent(QCloseEvent *event) {
      |      ^~~~~~~~~~~
/home/matt/gnuradio/gr-qtgui/examples/c++/Number_Sink/Number_Sink.cpp:100:6: note: ‘virtual void Number_Sink::closeEvent(QCloseEvent*)’ previously defined here
  100 | void Number_Sink::closeEvent(QCloseEvent *event) {
      |      ^~~~~~~~~~~
gmake[2]: *** [CMakeFiles/Number_Sink.dir/build.make:96: CMakeFiles/Number_Sink.dir/Number_Sink.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:86: CMakeFiles/Number_Sink.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2

>>> Done (return code 2)
```

### PR DESCRIPTION
**Pull request by dl1ksv**
## Description

Sometimes closeEvent is defined several times. In case of building qt cpp code, closeEvent may only be defined once.

This bug was introduced with #7411

## Related Issue

Fixes #7500
Fixes #7488

## Testing Done

Run the example mentioned in #7500 
## Checklist

- [x] I have read the [CONTRIBUTING document](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md).
- [x] I have squashed my commits to have one significant change per commit. 
- [x] I [have signed my commits before making this PR](https://github.com/gnuradio/gnuradio/blob/main/CONTRIBUTING.md#dco-signed)
- [ ] My code follows the code style of this project. See [GREP1.md](https://github.com/gnuradio/greps/blob/main/grep-0001-coding-guidelines.md).
- [ ] I have updated [the documentation](https://wiki.gnuradio.org/index.php/Main_Page#Documentation) where necessary.
- [ ] I have added tests to cover my changes, and all previous tests pass.

### CODE REVIEW

**Comment by willcode** [comment]
Yes, this is the same problem as in #7500, which was marked as fixed.
